package main

import (
	"fmt"

	"github.com/ristoavila/nilan"
)

func main() {
	fmt.Println("Test")
	c := nilan.Controller{Config: nilan.Config{NilanAddress: "/dev/ttyUSB1"}}
	readings, _ := c.FetchReadings()
	fmt.Println(readings)
	fmt.Printf("T0Controller: %.2f\n", float64(readings.T0Controller)/100)
	fmt.Printf("T1InTakeTemp: %.2f\n", float64(readings.T1InTakeTemp)/100)
	fmt.Printf("T2InletTemp: %.2f\n", float64(readings.T2InletTemp)/100)
	fmt.Printf("T3ExhaustTemp: %.2f\n", float64(readings.T3ExhaustTemp)/100)
	fmt.Printf("T4OutletTemp: %.2f\n", float64(readings.T4OutletTemp)/100)
	fmt.Printf("T5CondTemp: %.2f\n", float64(readings.T5CondTemp)/100)
	fmt.Printf("T6EvapTemp: %.2f\n", float64(readings.T6EvapTemp)/100)
	fmt.Printf("T7InletTemp: %.2f\n", float64(readings.T7InletTemp)/100)
	fmt.Printf("T8OutdoorTemp: %.2f\n", float64(readings.T8OutdoorTemp)/100)
	fmt.Printf("T9HeaterTemp: %.2f\n", float64(readings.T9HeaterTemp)/100)
	fmt.Printf("T10ExtTemp: %.2f\n", float64(readings.T10ExtTemp)/100)
	fmt.Printf("T11HotWaterTopTemp: %.2f\n", float64(readings.T11HotWaterTopTemp)/100)
	fmt.Printf("T12HotWaterBottomTemp: %.2f\n", float64(readings.T12HotWaterBottomTemp)/100)
	fmt.Printf("T13ReturnTemp: %.2f\n", float64(readings.T13ReturnTemp)/100)
	fmt.Printf("T14SupplyTemp: %.2f\n", float64(readings.T14SupplyTemp)/100)
	fmt.Printf("T15RoomTemp: %.2f\n", float64(readings.T15RoomTemp)/100)
	fmt.Printf("RelativeHumidity: %.2f\n", float64(readings.RelativeHumidity)/100)
	fmt.Printf("CO2: %d\n", readings.CO2)

	fmt.Printf("AlarmStatus: %d ", readings.AlarmStatus)
	fmt.Printf("AlarmID1: %d ", readings.AlarmID1)
	fmt.Printf("AlarmID2: %d ", readings.AlarmID2)
	fmt.Printf("AlarmID3: %d\n", readings.AlarmID3)

	fmt.Printf("ControlRunAct: %d ", readings.ControlRunAct)
	fmt.Printf("ControlModeAct: %d ", readings.ControlModeAct)
	fmt.Printf("ControlState: %d ", readings.ControlState)
	fmt.Printf("ControlSecInState: %d\n", readings.ControlSecInState)
	fmt.Printf("VentSetAct: %d ", readings.VentSetAct)
	fmt.Printf("InletAct: %d ", readings.InletAct)
	fmt.Printf("ExhaustAct: %d\n", readings.ExhaustAct)
	fmt.Printf("SinceFiltDay: %d\n", readings.SinceFiltDay)
	fmt.Printf("ToFiltDay: %d\n", readings.ToFiltDay)
	fmt.Printf("IsSummer: %d\n", readings.IsSummer)
	fmt.Printf("TemperatureSet: %.2f\n", float64(readings.TemperatureSet)/100)
	fmt.Printf("TempControl:%.2f\n", float64(readings.TempControl)/100)
	fmt.Printf("TempRoom:%.2f\n", float64(readings.TempRoom)/100)
	fmt.Printf("Efficiency: %.2f\n", float64(readings.Efficiency)/100)
	fmt.Printf("RequestedCapacity: %.2f\n", float64(readings.RequestedCapacity)/100)
	fmt.Printf("ActualCapacity: %.2f\n", float64(readings.ActualCapacity)/100)
	fmt.Printf("HotWaterType: %d\n", readings.HotWaterType)
	fmt.Printf("HotWaterAnodeState: %d\n", readings.HotWaterAnodeState)
	fmt.Printf("DisplayLed1: %d ", readings.DisplayLed1)
	fmt.Printf("DisplayLed2: %d\n", readings.DisplayLed2)
	fmt.Printf("HeatExtSet:%.2f\n", float64(readings.HeatExtSet)/100)
	errors, _ := c.FetchErrors()
	fmt.Println(errors)

	readholdings, _ := c.FetchHoldingRegisters()
	fmt.Println(readholdings)

	fmt.Printf("Compressor: %d \n", readholdings.Compressor)
	fmt.Printf("WatherHeat: %d \n", readholdings.WatherHeat)
	fmt.Printf("CenCircPump: %d ", readholdings.CenCircPump)
	fmt.Printf("CenHeat1: %d ", readholdings.CenHeat1)
	fmt.Printf("CenHeat2: %d ", readholdings.CenHeat2)
	fmt.Printf("CenHeat3: %d ", readholdings.CenHeat3)
	fmt.Printf("CenHeatExt: %d \n", readholdings.CenHeatExt)
	fmt.Printf("Defrosting: %d \n", readholdings.Defrosting)
	fmt.Printf("ExhaustFanSpeed: %.2f ", float64(readholdings.ExhaustFanSpeed)/100)
	fmt.Printf("InletFanSpeed:  %.2f\n", float64(readholdings.InletFanSpeed)/100)
	fmt.Printf("AirHeatCap: %.2f ", float64(readholdings.AirHeatCap)/100)
	fmt.Printf("CenHeatCap: %.2f ", float64(readholdings.CenHeatCap)/100)
	fmt.Printf("CompresorCap: %.2f\n", float64(readholdings.CompresorCap)/100)
	fmt.Printf("ControlRunSet: %d \n", readholdings.ControlRunSet)
	fmt.Printf("ControlModeSet: %d \n", readholdings.ControlModeSet)
	fmt.Printf("ControlVentSet: %d \n", readholdings.ControlVentSet)
	fmt.Printf("ControlTempSet: %.2f\n", float64(readholdings.ControlTempSet)/100)
	fmt.Printf("CoolVent: %d ", readholdings.CoolVent)
	fmt.Printf("CoolSet: %d \n", readholdings.CoolSet)
	fmt.Printf("SummerTempMin: %.2f\n", float64(readholdings.SummerTempMin)/100)
	fmt.Printf("WinterTempMin: %.2f\n", float64(readholdings.WinterTempMin)/100)
	fmt.Printf("SummerTempMax: %.2f\n", float64(readholdings.SummerTempMax)/100)
	fmt.Printf("WinterTempMax: %.2f\n", float64(readholdings.WinterTempMax)/100)
	fmt.Printf("SummerTempLimit: %.2f\n", float64(readholdings.SummerTempLimit)/100)
	fmt.Printf("HotWaterTempElectricT11: %.2f\n", float64(readholdings.HotWaterTempElectricT11)/100)
	fmt.Printf("HotWaterTempCompressorT12: %.2f\n", float64(readholdings.HotWaterTempCompressorT12)/100)
}
